Repository NethermindEth/wei, pull requests merged in 2025-08, with the labels that each got.

#9 feat: add rust CI
  .github/workflows/ci.yml
  crates/agent/src/services/webhook.rs
  crates/agent/src/utils/error.rs
  crates/agent/tests/integration_test.rs
  crates/indexer/src/utils/error.rs
  crates/indexer/tests/integration_test.rs
Labels: ci/cd

#12 feat: add react project
  ui/.gitignore
  ui/README.md
  ui/eslint.config.mjs
  ui/next.config.ts
  ui/package.json
  ui/pnpm-lock.yaml
  ui/postcss.config.mjs
  ui/public/wei.png
  ui/src/app/favicon.ico
  ui/src/app/globals.css
  ui/src/app/layout.tsx
  ui/src/app/page.tsx
  ui/src/app/providers.tsx
  ui/src/components/analyzer/analyzer-client.tsx
  ui/src/components/analyzer/hero-cta.tsx
  ui/tsconfig.json
Labels: frontend

#14 feat: add dev instructions to README
  README.md
Labels: documentation

#21 feat: dockerize rust
  .gitignore
  Cargo.lock
  DOCKER.md
  Dockerfile
  README.md
  docker-compose.yml
  docker/init-db.sh
Labels: ci/cd

#15 feat: add configs, analyze endpoint, openrouter integration
  Cargo.toml
  crates/agent/Cargo.toml
  crates/agent/src/api/handlers.rs
  crates/agent/src/api/routes.rs
  crates/agent/src/config/mod.rs
  crates/agent/src/db/core.rs
  crates/agent/src/db/mod.rs
  crates/agent/src/lib.rs
  crates/agent/src/main.rs
  crates/agent/src/models/proposal.rs
  crates/agent/src/prompts/mod.rs
  crates/agent/src/services/agent.rs
  crates/agent/src/services/ai.rs
  crates/agent/src/services/mod.rs
  crates/agent/src/utils/error.rs
  crates/agent/src/utils/mod.rs
  crates/agent/src/utils/validation.rs
  crates/indexer/Cargo.toml
  crates/indexer/src/config/mod.rs
  crates/indexer/src/main.rs
  crates/indexer/src/utils/error.rs
  crates/indexer/tests/integration_test.rs
  env.example
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/components/analyzer/analyzer-client.tsx
  ui/src/components/analyzer/markdown-renderer.tsx
  ui/src/config/api.ts
  ui/src/services/api.ts
  ui/src/types/proposal.ts
Labels: backend

#24 Include strict Nodejs and packages version
  ui/.nvmrc
  ui/package.json
Labels: enhancement, frontend

#34 Fix error handling
  crates/agent/src/api/error.rs
  crates/agent/src/api/handlers.rs
  crates/agent/src/api/middleware.rs
  crates/agent/src/api/mod.rs
  crates/agent/src/api/routes.rs
Labels: backend

#35 feat: expand the analysis report
  crates/agent/src/api/handlers.rs
  crates/agent/src/models/analysis.rs
  crates/agent/src/prompts/mod.rs
  crates/agent/src/services/agent.rs
  ui/src/components/analyzer/analyzer-client.tsx
  ui/src/types/proposal.ts
Labels: backend

#63 feat: include issue and pull request templates in .github directory
  .github/issue_template.md
  .github/pull_request_template.md
Labels: documentation, enhancement

#41 feat: add documentation for technical analysis
  .gitignore
  docs/AI Agent Evaluation/Evaluation Process For Wei 247360fc38d08018bf69ef9d0a18c081.md
  docs/Good Proposals examples/Good Proposals 246360fc38d080d4b904ec3aa558ae8e.md
  docs/Indexer Analysis/Technical analysis for the indexer 246360fc38d080fd8979e594a09a0acb.md
  docs/Indexer Analysis/Technical analysis for the indexer 246360fc38d080fd8979e594a09a0acb/image.png
  docs/Questions To Decide If The Agent Is Good/Questions To Decide whether Wei Works Well 247360fc38d0804fb467ebb1b2726053.md
Labels: documentation

#49 refact: error handling
  crates/agent/src/api/error.rs
  crates/agent/src/api/handlers.rs
  crates/agent/src/api/middleware.rs
  crates/agent/src/api/routes.rs
Labels: enhancement, backend

#44 Integrate snapshot api
  ui/src/components/proposals/proposal-card.tsx
  ui/src/components/proposals/proposal-list.tsx
Labels: frontend

#45 Release beta v0.0.2
  .github/issue_template.md
  .github/pull_request_template.md
  .gitignore
  README.md
  crates/agent/src/api/error.rs
  crates/agent/src/api/handlers.rs
  crates/agent/src/api/middleware.rs
  crates/agent/src/api/routes.rs
  crates/agent/src/db/core.rs
  crates/agent/src/main.rs
  crates/agent/src/models/analysis.rs
  crates/agent/src/prompts/mod.rs
  crates/agent/src/services/agent.rs
  crates/agent/tests/api_key_auth_tests.rs
  docs/AI Agent Evaluation/Evaluation Process For Wei 247360fc38d08018bf69ef9d0a18c081.md
  docs/Good Proposals examples/Good Proposals 246360fc38d080d4b904ec3aa558ae8e.md
  docs/Indexer Analysis/Technical analysis for the indexer 246360fc38d080fd8979e594a09a0acb.md
  docs/Indexer Analysis/Technical analysis for the indexer 246360fc38d080fd8979e594a09a0acb/image.png
  docs/Questions To Decide If The Agent Is Good/Questions To Decide whether Wei Works Well 247360fc38d0804fb467ebb1b2726053.md
  ui/env.example
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/app/layout.tsx
  ui/src/components/analyzer/analyzer-client.tsx
  ui/src/components/proposals/proposal-card.tsx
  ui/src/components/proposals/proposal-list.tsx
  ui/src/components/ui/markdown-styles.css
  ui/src/components/ui/modal.tsx
  ui/src/config/api.ts
  ui/src/hooks/useProposals.ts
  ui/src/queries/proposals.gql.ts
  ui/src/services/api.ts
  ui/src/services/graphql.ts
  ui/src/types/proposal.ts
Labels: release
